// DO NOT EDIT.
// This file was automatically generated by sfm-designer-solver.
//
// Each key in the solution is the number of reflections in the interferometer.
const SOLUTIONS = {
  2: [
    { value: 0, solution: [0, 1], name: '[0, 1]' },
  ],
  3: [
    { value: 0, solution: [0, 1, 3], name: '[0, 1, 3]' },
    { value: 1, solution: [0, 2, 3], name: '[0, 2, 3]' },
  ],
  4: [
    { value: 0, solution: [0, 1, 4, 6], name: '[0, 1, 4, 6]' },
    { value: 1, solution: [0, 2, 5, 6], name: '[0, 2, 5, 6]' },
  ],
  5: [
    { value: 0, solution: [0, 1, 4, 9, 11], name: '[0, 1, 4, 9, 11]' },
    { value: 1, solution: [0, 2, 7, 8, 11], name: '[0, 2, 7, 8, 11]' },
    { value: 2, solution: [0, 2, 7, 10, 11], name: '[0, 2, 7, 10, 11]' },
    { value: 3, solution: [0, 3, 4, 9, 11], name: '[0, 3, 4, 9, 11]' },
  ],
  6: [
    { value: 0, solution: [0, 1, 4, 10, 12, 17], name: '[0, 1, 4, 10, 12, 17]' },
    { value: 1, solution: [0, 1, 4, 10, 15, 17], name: '[0, 1, 4, 10, 15, 17]' },
    { value: 2, solution: [0, 1, 8, 11, 13, 17], name: '[0, 1, 8, 11, 13, 17]' },
    { value: 3, solution: [0, 1, 8, 12, 14, 17], name: '[0, 1, 8, 12, 14, 17]' },
    { value: 4, solution: [0, 2, 7, 13, 16, 17], name: '[0, 2, 7, 13, 16, 17]' },
    { value: 5, solution: [0, 3, 5, 9, 16, 17], name: '[0, 3, 5, 9, 16, 17]' },
    { value: 6, solution: [0, 4, 6, 9, 16, 17], name: '[0, 4, 6, 9, 16, 17]' },
    { value: 7, solution: [0, 5, 7, 13, 16, 17], name: '[0, 5, 7, 13, 16, 17]' },
  ],
  7: [
    { value: 0, solution: [0, 1, 4, 10, 18, 23, 25], name: '[0, 1, 4, 10, 18, 23, 25]' },
    { value: 1, solution: [0, 1, 7, 11, 20, 23, 25], name: '[0, 1, 7, 11, 20, 23, 25]' },
    { value: 2, solution: [0, 1, 11, 16, 19, 23, 25], name: '[0, 1, 11, 16, 19, 23, 25]' },
    { value: 3, solution: [0, 2, 3, 10, 16, 21, 25], name: '[0, 2, 3, 10, 16, 21, 25]' },
    { value: 4, solution: [0, 2, 5, 14, 18, 24, 25], name: '[0, 2, 5, 14, 18, 24, 25]' },
    { value: 5, solution: [0, 2, 6, 9, 14, 24, 25], name: '[0, 2, 6, 9, 14, 24, 25]' },
    { value: 6, solution: [0, 2, 7, 13, 21, 22, 25], name: '[0, 2, 7, 13, 21, 22, 25]' },
    { value: 7, solution: [0, 2, 7, 15, 21, 24, 25], name: '[0, 2, 7, 15, 21, 24, 25]' },
    { value: 8, solution: [0, 3, 4, 12, 18, 23, 25], name: '[0, 3, 4, 12, 18, 23, 25]' },
    { value: 9, solution: [0, 4, 9, 15, 22, 23, 25], name: '[0, 4, 9, 15, 22, 23, 25]' },
  ],
  8: [
    { value: 0, solution: [0, 1, 4, 9, 15, 22, 32, 34], name: '[0, 1, 4, 9, 15, 22, 32, 34]' },
    { value: 1, solution: [0, 2, 12, 19, 25, 30, 33, 34], name: '[0, 2, 12, 19, 25, 30, 33, 34]' },
  ],
  9: [
    { value: 0, solution: [0, 1, 5, 12, 25, 27, 35, 41, 44], name: '[0, 1, 5, 12, 25, 27, 35, 41, 44]' },
    { value: 1, solution: [0, 3, 9, 17, 19, 32, 39, 43, 44], name: '[0, 3, 9, 17, 19, 32, 39, 43, 44]' },
  ],
  10: [
    { value: 0, solution: [0, 1, 6, 10, 23, 26, 34, 41, 53, 55], name: '[0, 1, 6, 10, 23, 26, 34, 41, 53, 55]' },
    { value: 1, solution: [0, 2, 14, 21, 29, 32, 45, 49, 54, 55], name: '[0, 2, 14, 21, 29, 32, 45, 49, 54, 55]' },
  ],
};

export default SOLUTIONS;
